### ISSUE TITLE
Sample_ID and Individual_ID should import as integers

### ISSUE THREAD

**Issue by doridick14** [genegis/genegis#37]
The current Classified data import tool, imports the Sample_ID and Individual_ID fields as strings and not integer values.

For SPLASH, I would have expected both to come in as integers.  However, since it is possible that these fields could also be text or alpha-numeric values in another dataset, it would be useful to have the script automatically figure out which data type it is or have the user select the most appropriate data type.

**Comment by holmbergius** [comment]
What would be the advantage of considering them as other than strings? I
don't think they're used for comparison or calculation.

On Wednesday, March 13, 2013, Dori Dick wrote:

> The current Classified data import tool, imports the Sample_ID and
> Individual_ID fields as strings and not integer values.
> 
> For SPLASH, I would have expected both to come in as integers. However,
> since it is possible that these fields could also be text or alpha-numeric
> values in another dataset, it would be useful to have the script
> automatically figure out which data type it is or have the user select the
> most appropriate data type.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EsriOceans/genegis/issues/37
> .

## 

Jason Holmberg
ECOCEAN Whale Shark Photo-identification Library
http://www.whaleshark.org

Please consider adopting a shark to support our mission:
http://www.whaleshark.org/adoptashark.jsp

**Comment by scw** [comment]
Yeah, I guess I can see it both ways. If the data is maintaining referential integrity, then perhaps numerical values would make good sense so we can maintain the relationships. On the other hand, some folks will have strange composite keys (e.g. AKNorthSea001) which would need to be strings anyway.

**Comment by doridick14** [comment]
A good point, however, if the values for Sample_ID and Individual_ID are numbers going in and we maintain that data type, then the user can more easily sort the records or conduct some basic summary statistics. [As a SPLASH aside, I seem to recall Erin Falcone mentioning the SPLASH_ID was a numeric value so that it could be easily sorted for her needs].

For example, I loaded in the data into ArcGIS and wanted to know how many unique individuals there were in the dataset or quickly create a histogram to look at the frequency of individual occurrence in the data, I would need the field to be an integer.  These are things Scott has expressed would be nice to do.  We can get around this by creating a tool that does this, which I believe is on the list but doesn't exist yet.  

Unfortunately, this would not address the composite keys Shaun mentioned (e.g. AKNorthSea001).  So I guess we need to consider how to handle this, too.  Thoughts?

**Comment by scw** [comment]
One option is we do some very basic heuristics against the data, and go from there. Something along the lines of: read in the first value or two, see if they cast to integers cleanly, and if so, use a numeric type, otherwise keep them as strings. How hard would that be to gin up on your end Jason? I don't want to make this overly complex, but can see the use of doing both.

**Comment by holmbergius** [comment]
_How hard would that be to gin up on your end Jason?_

So the Shepherd Project uses int as the identifier (jst generates a random
number) but treats it as a String, so it's not really an issue for me. By
default, I will provide you with the int, but I can handle whatever people
use. So I think the adaptation will only be required on your end.
