### ISSUE TITLE
Export to GenAlEx replace empty/nullvalues with zeros

### ISSUE THREAD

**Issue by doridick14** [genegis/genegis#98]
Empty fields (null values) in a feature class export to GenAlEx as blanks. Need to revised so that empty fields export as zeros so that GenAlEx will work.

**Comment by scw** [comment]
Hi Dori,

I've fixed this as far as I can tell, now any NULL values in the output rows will have a '0' instead of an empty field. I've added a test case to make sure this works, and can confirm that zeros show up in the output. If you could test as well that'd be great. Thanks!
